### ISSUE TITLE
Is it normal to get a "None of the pools have an opened connection" error?

### ISSUE THREAD

**Issue by helloitsm3** [JoeBiellik/pleasenospam#23]
![image](https://user-images.githubusercontent.com/13825491/52907839-9b1e7280-32a4-11e9-963e-c4c8e3035baa.png)

**Comment by JoeBiellik** [comment]
No, you can see from the error message it is unable to connect to your database. Verify your database is correctly configured and started and that you are using the correct connection details in the configuration.
