### ISSUE TITLE
Why does pns need canvas data?

### ISSUE THREAD

**Issue by vc7ee** [JoeBiellik/pleasenospam#25]
![image](https://user-images.githubusercontent.com/38327267/58233342-5daa0500-7d2b-11e9-8bed-01efe02029b0.png)

**Comment by JoeBiellik** [comment]
[favico.js](http://lab.ejci.net/favico.js/) is using canvas to take the websites favicon and writing the number of emails onto the image, as a quick indicator in the tab title.

If you don't want to allow the site to use canvas, it should still function fine, just without the live email count favicon.
