### ISSUE TITLE
Configuration with Traefik

### ISSUE THREAD

**Issue by vc7ee** [JoeBiellik/pleasenospam#26]
Hey, looking to deploy this with Traefik, but any ideas how would you forward the incoming mail, when there is an another mail server (with different domains) running on the same server? DNS config?

**Comment by JoeBiellik** [comment]
I'm not familiar with Traefik so I cant give you any direct instructions, but it sounds feasible. The mail server component of this app is just SMTP, so their are various ways of routing it.

If its just a matter of wanting domain `example1.com` to go to a real mail server and domain `example2.com` to be used by pleasenospam then its as simple as setting MX records to point each to a different external IP, with each application listening on that IP port 25.

If your goal is to run multiple mail servers connected to a single external IP, then I would look into SMTP relays or using a mail server that is capable of forwarding mail based on domain as your externally facing mail server. I'm no expert but I think [you can do this in Postfix](http://www.postfix.org/postconf.5.html#relay_domains) with [transport tables](http://www.postfix.org/transport.5.html).

Worst case you can always modify this project to not run its own mail server, but to instead get the emails from another mail server's files or database.

**Comment by vc7ee** [comment]
I hate mail.

**Comment by JoeBiellik** [comment]
Its pretty painful. Reopen if you need specific details.
