### ISSUE TITLE
There seems to be some issue with the server

### ISSUE THREAD

**Issue by helloitsm3** [JoeBiellik/pleasenospam#32]
![image](https://user-images.githubusercontent.com/13825491/74600712-5a805180-50d0-11ea-8b93-28bfa44044a1.png)

**Comment by jtagcat** [comment]
#28 #29 
The DB server probably crashed, cc @JoeBiellik 
I think I can take over the hosting, if needed. While I use the pleasenospam, I don't see the point of dedicating a domain of mine's mail to pns.

**Comment by helloitsm3** [comment]
> 
> 
> #28 #29
> The DB server probably crashed, cc @JoeBiellik
> I think I can take over the hosting, if needed. While I use the pleasenospam, I don't see the point of dedicating a domain of mine's mail to pns.

Do let me know once you've taken over. Would be interested to take a look. Seems like @JoeBiellik is busy updating it

**Comment by jtagcat** [comment]
@helloitsm3 What would there be to take a look at?(?)

**Comment by JoeBiellik** [comment]
Yeah Rethink had crashed, restarted now. @jtagcat appreciate the offer, but its less about hosting bandwidth and more about Rethink periodically crashing. I think I'll just setup cron to restart it every couple of months.

I'll try to get this projects dependencies updated and maybe add a couple of new features this week.
